"""Add health tracking models

Revision ID: 54b3c1ff5f9c
Revises: 1d15fb8a1bdb
Create Date: 2025-04-28 15:55:32.176392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b3c1ff5f9c'
down_revision = '1d15fb8a1bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_date_metrics')
    )
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_daily_metrics_user_date', ['user_id', 'date'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index('idx_exercises_user_date', ['user_id', 'date'], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=False),
    sa.Column('food_detail', sa.Text(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index('idx_meals_user_date', ['user_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index('idx_meals_user_date')

    op.drop_table('meals')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index('idx_exercises_user_date')

    op.drop_table('exercises')
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_metrics_user_date')

    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
