"""Add height and weight fields to User model

Revision ID: 7b39ac87d94d
Revises: 8c27717be12c
Create Date: 2025-05-04 17:38:37.114161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b39ac87d94d'
down_revision = '8c27717be12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
