"""add user goal table for weight tracking

Revision ID: 8ab9b91786f5
Revises: 96e39f132131
Create Date: 2025-05-13 19:26:38.555935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab9b91786f5'
down_revision = '96e39f132131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('initial_weight', sa.Float(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_goals')
    # ### end Alembic commands ###
