"""Initial migration: create all tables

Revision ID: b00524eb9346
Revises: 54b3c1ff5f9c
Create Date: 2025-04-29 17:58:00.706434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00524eb9346'
down_revision = '54b3c1ff5f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('calorie_burns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise_type_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_type_id'], ['exercise_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calorie_burns', schema=None) as batch_op:
        batch_op.create_index('idx_calorie_burns_user_date', ['user_id', 'date'], unique=False)

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index('idx_meals_user_date')

    op.drop_table('meals')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index('idx_exercises_user_date')

    op.drop_table('exercises')
    with op.batch_alter_table('calorie_entries', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('food_detail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calorie_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_detail', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.VARCHAR(length=255), nullable=True))

    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('calories_burned', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index('idx_exercises_user_date', ['user_id', 'date'], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('food_detail', sa.TEXT(), nullable=False),
    sa.Column('calories', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index('idx_meals_user_date', ['user_id', 'date'], unique=False)

    with op.batch_alter_table('calorie_burns', schema=None) as batch_op:
        batch_op.drop_index('idx_calorie_burns_user_date')

    op.drop_table('calorie_burns')
    op.drop_table('exercise_types')
    # ### end Alembic commands ###
