"""sync database for updates in models

Revision ID: ee6f28b54459
Revises: 8ab9b91786f5
Create Date: 2025-05-16 01:06:34.385079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6f28b54459'
down_revision = '8ab9b91786f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('sugars', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    with op.batch_alter_table('calorie_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carbohydrates', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('proteins', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fats', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sugars', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fiber', sa.Float(), nullable=False))
        batch_op.alter_column('calories',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index('idx_verification_codes', ['user_id', 'code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index('idx_verification_codes')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('calorie_entries', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('fiber')
        batch_op.drop_column('sugars')
        batch_op.drop_column('fats')
        batch_op.drop_column('proteins')
        batch_op.drop_column('carbohydrates')

    op.drop_table('foods')
    # ### end Alembic commands ###
