name: Create branch on issue creation
on:
  issues:
    types: [opened]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create branch name
        id: branch
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE="${{ github.event.issue.title }}"

          # Sanitize title into kebab-case
          BRANCH_TITLE=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-+|-+$//g')
          BRANCH_NAME="issue/${ISSUE_NUMBER}-${BRANCH_TITLE}"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git checkout -b ${{ steps.branch.outputs.BRANCH_NAME }} origin/main
          git push origin ${{ steps.branch.outputs.BRANCH_NAME }}
