name: Run Python & Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python -m tests.run_tests unit

      - name: Start Flask App in Background
        run: |
          nohup python app.py &
          sleep 5  # 给 Flask 足够的时间启动

      - name: Run Selenium Tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          # 逐个运行 Selenium 测试以避免端口冲突
          python -m tests.run_tests login_page
          python -m tests.run_tests login_success
          python -m tests.run_tests login_failure
          python -m tests.run_tests registration
          python -m tests.run_tests track_exercise
          python -m tests.run_tests view_profile

      - name: Archive test screenshots if needed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: screenshots/
